services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Plenta\ProtectedSelect\:
            resource: ../src
            exclude: ../src/{Entity,Migrations,Resources,Tests,Classes}